<h2>About the Platform</h2>

<p>This is an instance of the <a href="http://inl.github.io/BlackLab/" target="_blank">Blacklab corpus search engine</a> developed by the <a href="https://www.ivdnt.org/" target="_blank">Dutch Language Institute</a>. It is hosted by <a href="https://alpheios.net" target="_blank">The Alpheios Project, Ltd.</a>.</p>

<h2>About the Corpus</h2>

<dl>
<dt>Title</dt><dd property="http://purl.org/dc/elements/1.1/title"><a href="https://github.com/lascivaroma/latin-lemmatized-texts" target="_blank">lascivaroma/latin-lemmatized-texts</a>: 0.0.1 - Première version</dd>
<dt>Creator</dt><dd property="http://purl.org/dc/elements/1.1/creator">Thibault Clérice</dd>
<dt>Date</dt><dd property="http://purl.org/dc/elements/1.1/date">2020-12-17</dd>
<dt>Description</dt><dd property="http://purl.org/dc/elements/1.1/description">Tagged corpora with metadata</dd>
<dt>Identifier</dt><dd property="http://purl.org/dc/elements/1.1/identifier">http://doi.org/10.5281/zenodo.4337146</dd>
<dt>License (annotations)<dt><dd property="http://purl.org/dc/elements/1.1/license">https://creativecommons.org/licenses/by-sa/4.0/</dd>
<dt>License (texts)<dt><dd>Per corpus source (see below).</dd>
</dl>


<h3>Source Texts</h3>
<p>The source texts are composed of the set of openly available <a href="http://capitains.org/" target="_blank">capitains-compliant</a> classical and late Latin texts:</p>

<table>
<thead>
<tr><th>Name</th><th>Version</th><th>Project</th></tr>
</thead>
<tbody>
<tr><td><a href="https://github.com/PerseusDL/canonical-latinLit" target="_blank">PerseusDL/canonical-latinLit</a></td><td>0.0.557</td><td><a href="https://www.perseus.org" target="_blank">https://www.perseus.org</a></td></tr>
<tr><td><a href="https://github.com/OpenGreekAndLatin/csel-dev" target="_blank">OpenGreekAndLatin/csel-dev</a></td><td>1.0.67</td><td><a href="https://www.perseus.org" target="_blank">https://www.perseus.org</a></td></tr>
<tr><td><a href="https://github.com/OpenGreekAndLatin/Latin" target="_blank">OpenGreekAndLatin/Latin</a></td><td>v1.10.0</td><td><a href="https://www.perseus.org" target="blank">https://www.perseus.org</a></td></tr>
<tr><td><a href="https://github.com/ponteineptique/digiliblt" target="_blank">ponteineptique/digiliblt</a></td><td>0.0.32</td><td><a href="https://digiliblt.uniupo.it" target="_blank">https://gitiliblt.uniupo.it</a></td></tr>
<tr><td><a href="https://github.com/lascivaroma/priapeia" target="_blank">lascivaroma/priapeia</a></td><td>1.1.18</td><td><a href="https://github.com/lascivaroma" target="_blank">Lasciva Roma</a></td></tr>
<tr><td><a href="https://github.com/lascivaroma/additional-texts" target="_blank">lascivaroma/additional-texts</a></td><td>1.0.115</td><td><a href="https://github.com/lascivaroma" target="_blank">Lasciva Roma</a></td></tr>
</tbody>
</table>


<h3>Annotations</h3>
<p>The corpus has been automatically annotated using models trained on the <a href="http://web.philo.ulg.ac.be/lasla/textes-latins-traites/" target="_blank">LASLA Textes latin traités</a>.  For more information about the models and source data see <a href="https://https://github.com/lascivaroma/latin-lemmatized-texts" target="_blank">https://github.com/lascivaroma/latin-lemmatized-texts</a>.</p>

