<h2>Corpus Search Tips</h2>

<p class="hint">Note: For general platform search capabilities, see the Page Guide.</p>

<h4>The following <b>token attributes</b> are available for searching:</h4>

<table>
<thead>
<tr><th>Attribute</th><th>Description</th><th>Example</th></tr>
</thead>
<tbody>
<tr><td>word</td><td>The text of a word.</td><td>mare</td></tr>
<td>lemma</td><td>The text of the lemma of a word.</td><td>mas</td></tr>
<td>pos</td><td>The part of speech of a word, as encoded via TBD</td><td>NOM</td></tr>
<tr><td>msd</td><td>The morphological features of a word, as encoded via the <a href="https://universaldependencies.org/format.html" target="_blank">CONLL-U</a> format of <a href="https://universaldependencies.org/u/feat/index.html" target="_blank">Universal Dependencies Morphological Features</a> tagset.</td><td>Case=Nom|Numb=Sing</td></tr>
<tr><td>ref</td><td>The passage reference in which a word is found.</td><td>86<td></tr>
<tr><td>in</td><td>The reference type of the parent citable passage</td><td>line</td></tr>
</table>

<h4>The following corpus metadata <b>filters</b> can be applied to search results:</h4>

<table>
<thead>
<tr><th>Filter</th><th>Description</th><th>Example</th></tr>
</thead>
<tbody>
<tr><td>Author</td><td>The author of a work.</td><td>Caesar</td></tr>
<tr><td>Title</td><td>The title of a work.</td><td>Caesar</td></tr>
<td>Doc id</td><td>The identifier of the edition.</td><td>urn:cts:latinLit:phi0448.phi002.perseus-lat2</td></tr>
<td>Input file</td><td>The path to the source file</td><td>/xml/urn:cts:latinLit:phi0448.phi002.perseus-lat2.xml</td></tr>
</table>


